# Fly.io configuration for NebulaMind
app = "nebulamind"
primary_region = "fra"

[build]
  dockerfile = "cicd/fly/Dockerfile"

[env]
  SPRING_PROFILES_ACTIVE = "production"
  CORE_PORT = "8081"
  AGENT_PORT = "8082"
  LOG_DIR = "/app/logs"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/api/core/health"
    protocol = "http"
    tls_skip_verify = false

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/api/agent/health"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

